First part
AxelCalas/java-bootcamp-2018-Goal0-Axel-Calas pull request #1
Opened 2018-09-26 06:39 UTC by AxelCalas

Pepe and javi, here is the Topic 0 finished ready to review.

2018-09-28 11:24 UTC, javiersvg requested changes

2018-09-28 11:24 UTC, javiersvg commented on src/main/java/abstracFactory/MySqlConnection.java
> +    String UserName,Password;
definir las variables en lineas separadas hace el codigo mas facil de leer

2018-09-28 11:24 UTC, javiersvg commented on src/main/java/abstracFactory/MySqlConnection.java
> +        UserName = User.nextLine();
recibir los valores por parametros hace que sea mucho mas facil de utilizar los metodos

2018-10-01 04:09 UTC, joseriquelme commented on src/main/java/abstracFactory/MySqlConnection.java
> +    String UserName,Password;
Hay que cuidar el encapsulamiento, hay que usar private

2018-10-01 04:15 UTC, joseriquelme requested changes

2018-10-01 04:15 UTC, joseriquelme commented on src/main/java/abstracFactory/Connection.java
> +    public void EnterUser();
public es redundante en una intefaz

2018-10-01 04:15 UTC, joseriquelme commented on src/main/java/builder/Connection.java
> +		return "Connection Type " + typeConnection + ", User: " + user + ", Passw:" + password;
indentacion

2018-10-01 04:15 UTC, joseriquelme commented on src/main/java/builder/FourthMain.java
> +    //Build a SQL Connection
the code should be self explanatory. Only add comments if there is no other option

2018-10-01 04:15 UTC, joseriquelme commented on src/main/java/proxy/ConnectionProxy.java
> +    Connection realConnection;
should be private

2018-10-01 04:15 UTC, joseriquelme commented on src/main/java/proxy/ConnectionProxy.java
> +    private String User;
class attributes should be in lower case

2018-10-01 04:15 UTC, joseriquelme commented on src/main/java/singleton/Program.java
> +	    DbConnection dbConnection = DbConnection.getInstance();
indentation

2018-10-18 23:24 UTC, merged